import turtle
turtle.speed(5)
turtle.bgcolor('white')
t = turtle.Pen()
 t.shape('turtle')
 t.goto(x=0,y=0)
 h = turtle.Pen()
 h.shape('classic')
 h.up()
 h.goto(x=0,y=200)
 h.down()
 y = turtle.Pen()
 y.shape('triangle')
 y.up()
 y.goto(x=-200,y=-200)
 y.down()
 r = turtle.Pen()
 r.shape('circle')
 r.up()
 r.goto(x=200,y=200)
 r.down()
 e = turtle.Pen()
 e.shape('square')
 e.up()
 e.goto(x=0,y=-200)
 e.down()
 t.color('red')
t.speed(250)
t.pensize(2.5)
t.fillcolor('black')
t.begin_fill()
for i in range(36):
     t.circle(100)
     t.left(50)
 t.end_fill()

turtle.mainloop()